spring.application.name=KaamKaaj

spring.security.user.name=harsh
spring.security.user.password=kittu

spring.datasource.url=jdbc:mysql://localhost:3306/KaamKaajv0?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true