spring.application.name=kaamkaaj

spring.security.user.name=harsh
spring.security.user.password=kittu

spring.datasource.url=jdbc:mysql://localhost:3306/kaamkaajv0?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

app.jwt.secret=2PYvxg/eWUJtGwjVlDMevP12b7QjYg4djRWp1WR9V6I=

app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.default-produces-media-type=application/json