spring.profiles.active=local
spring.application.name=kaamkaaj

sspring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/kaamkaajv0?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.cookies.secure=${COOKIES_SECURE:false}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.default-produces-media-type=application/json

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.task.scheduling.enabled=true